//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecast_Methods
    {
        public int ForecastMethodID { get; set; }
        public string ForecastMethod { get; set; }
        public string ForecastIdentifier { get; set; }
    }
}
