//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFC.Framework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDeliveryType
    {
        public FileDeliveryType()
        {
            this.ReportSchedules = new HashSet<ReportSchedule>();
        }
    
        public int DeliveryTypeId { get; set; }
        public string DeliveryMethod { get; set; }
    
        public virtual ICollection<ReportSchedule> ReportSchedules { get; set; }
    }
}
