//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFC.Framework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSchedule
    {
        public int ReportScheduleId { get; set; }
        public int ReportId { get; set; }
        public string ScheduleType { get; set; }
        public int ScheduleDay { get; set; }
        public System.TimeSpan ScheduleTime { get; set; }
        public string ScheduleDescription { get; set; }
        public string ReportSubscriptionId { get; set; }
    
        public virtual Report Report { get; set; }
    }
}
